project:
  type: website
  output-dir: ../../docs


website:
  title: "Learning Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - href: about.qmd
        # text: About
      - href: authoring.qmd
        text: Authoring
      - href: computational.qmd
        text: Computational
      - href: walkthrough.qmd
        text: Walk through

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



