project:
  type: website
  output-dir: ../../docs


website:
  title: "Learning Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: websites.qmd
        text: Websites
      - href: dashboard.qmd
        text: Dashboards
      - text: Examples
        menu: 
        - href: authoring.qmd
          text: Example 1
        - href: computational.qmd
          text: Example 2
        - href: walkthrough.qmd
          text: Example 3
        - href: http://angelofgdsantos.github.io/
          text: Personal website

format:
  html:
    theme:
      light: cosmo
      dark: lux
    toc: true
    style: style.css



